modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
	modId="autoleveling"
	version="1.6"
	displayName="Auto Leveling"
	authors="Daripher"
	description='''Adds auto leveling to Minecraft'''
