modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
	modId="autoleveling"
	version="1.12"
	displayName="Auto Leveling"
	authors="Daripher"
	description='''Adds auto leveling to Minecraft'''
